#!/usr/bin/env bash
# One-time Google-side setup for the live test suite (plan section 2.1).
#
# ---------------------------------------------------------------------------
# WHY A SHARED DRIVE IS NOT OPTIONAL
# ---------------------------------------------------------------------------
# A service account has no personal Drive storage quota. Uploading anything
# outside a Shared Drive returns:
#
#   403 "Service Accounts do not have storage quota. Leverage shared drives,
#        or use OAuth delegation instead."
#
# (Verified against the real API, 2026-07-26.) Folder *creation* succeeds --
# folders consume no quota -- which makes the failure look like a permissions
# problem right up until you try to upload a byte.
#
# A Shared Drive also cannot be created by a bare service account:
# drives.create requires a Google Workspace user identity. So step 4 below is
# genuinely manual, done once, by a data-zoo.de Workspace member.
# ---------------------------------------------------------------------------
set -euo pipefail

PROJECT="${GDRIVE_CI_PROJECT:-datazoo-gdrive-ci}"
SA_NAME="${GDRIVE_CI_SA_NAME:-gdrive-ci}"
SA_EMAIL="${SA_NAME}@${PROJECT}.iam.gserviceaccount.com"
KEY_OUT="${GDRIVE_CI_KEY_OUT:-.gcp-key.json}"

cat <<'BANNER'
================================================================================
 duckdb-gdrive :: one-time CI Drive setup
================================================================================
BANNER

step() { printf '\n\033[1m--> %s\033[0m\n' "$1"; }

step "1/5  Checking gcloud auth"
if ! gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | grep -q .; then
    echo "No active gcloud account. Run:  gcloud auth login" >&2
    exit 1
fi
echo "active: $(gcloud auth list --filter=status:ACTIVE --format='value(account)')"

step "2/5  Project + Drive API"
if ! gcloud projects describe "$PROJECT" >/dev/null 2>&1; then
    echo "Project '$PROJECT' not found."
    echo "Create it, or point at an existing one with GDRIVE_CI_PROJECT=<id>."
    exit 1
fi
gcloud services enable drive.googleapis.com --project="$PROJECT"
echo "drive.googleapis.com enabled on $PROJECT"

step "3/5  Service account"
if ! gcloud iam service-accounts describe "$SA_EMAIL" --project="$PROJECT" >/dev/null 2>&1; then
    gcloud iam service-accounts create "$SA_NAME" \
        --project="$PROJECT" \
        --display-name="duckdb-gdrive CI"
fi
echo "service account: $SA_EMAIL"

if [[ ! -f "$KEY_OUT" ]]; then
    gcloud iam service-accounts keys create "$KEY_OUT" \
        --iam-account="$SA_EMAIL" --project="$PROJECT"
    chmod 600 "$KEY_OUT"
    echo "key written to $KEY_OUT (0600, gitignored)"
else
    echo "key already present at $KEY_OUT -- not overwriting"
fi

step "4/5  MANUAL: create the Shared Drive"
cat <<MANUAL

  This step cannot be automated: creating a Shared Drive requires a Google
  Workspace *user* identity, which a service account does not have.

  As a data-zoo.de Workspace member:

    1. Open https://drive.google.com/drive/shared-drives
    2. New  ->  name it:  duckdb-gdrive-ci
    3. Open it  ->  Manage members  ->  add:

           $SA_EMAIL

       with the role **Content manager** (it must create and delete files).

    4. Copy the drive id from the URL:
           https://drive.google.com/drive/folders/<THIS_IS_THE_DRIVE_ID>

MANUAL

read -r -p "  Paste the Shared Drive id (or press Enter to skip): " DRIVE_ID || true

step "5/5  Writing .env.gdrive"
if [[ -n "${DRIVE_ID:-}" ]]; then
    cat > .env.gdrive <<ENV
# Generated by scripts/setup_ci_drive.sh -- NEVER COMMIT THIS FILE.
GDRIVE_CI_SA_KEY_FILE=$KEY_OUT
GDRIVE_CI_DRIVE_ID=$DRIVE_ID
ENV
    chmod 600 .env.gdrive
    echo "wrote .env.gdrive"
    echo ""
    echo "Next:"
    echo "  make seed_fixtures     # upload the permanent fixture tree"
    echo "  make e2e               # prove the harness works end to end"
else
    echo "skipped -- create .env.gdrive from .env.gdrive.example by hand."
fi

step "For CI"
cat <<CI
  Add these GitHub Actions secrets to DataZooDE/duckdb-gdrive:

    GDRIVE_CI_SA_KEY_B64   = \$(base64 -w0 $KEY_OUT)
    GDRIVE_CI_DRIVE_ID     = <the Shared Drive id>

  Rotate the local key file if it was ever shared.
CI
