"""Turn GDRIVE_TRACE_FILE span logs into the paper's timeline figure.

    python -m helpers.plot_timeline out.tex a.jsonl "label" b.jsonl "label" ...

One panel per trace, stacked, each with its own time axis because the runs
differ in length by 3x and a shared axis would squash the shortest into
nothing. Rows are threads; every bar is one Drive API call, coloured by kind.

The point of the figure is OVERLAP, not duration. A table of per-call medians
already says what a call costs; only a timeline shows that a DuckLake read
spends its first 1.7 s issuing six strictly sequential listings on one thread
before a single byte of data is requested.

Emits raw TikZ rather than pgfplots: a Gantt chart is rectangles, and going
through an axis environment to draw rectangles costs more than it gives.
"""

from __future__ import annotations

import json
import sys

# Colour per call kind. Media is the one that moves bytes, so it gets the
# strong colour; metadata calls are deliberately muted so that a panel which
# is mostly metadata LOOKS mostly grey.
KIND_STYLE = {
    "files.list": ("black!22", "list"),
    "files.get": ("black!45", "get"),
    "files.media": ("orange!80", "media"),
    "files.create": ("teal!70", "create"),
    "files.update": ("violet!55", "update"),
    "files.delete": ("red!55", "delete"),
    "files.export": ("blue!45", "export"),
}

PANEL_W = 16.0     # cm, drawing width of the time axis (figure* is ~17.8cm)
ROW_H = 0.34       # cm per thread row
BAR_H = 0.24       # cm
PANEL_GAP = 1.15   # cm between panels


def load(path: str) -> list[dict]:
    spans = []
    with open(path) as fh:
        for line in fh:
            d = json.loads(line)
            if d.get("record") == "header":
                continue
            spans.append(d)
    return spans


def nice_ticks(span_s: float) -> list[float]:
    step = next(s for s in (0.5, 1.0, 2.0, 5.0, 10.0) if span_s / s <= 8)
    out, t = [], 0.0
    while t <= span_s + 1e-9:
        out.append(round(t, 3))
        t += step
    return out


def panel(spans: list[dict], label: str, y_top: float) -> tuple[list[str], float]:
    """Draw one panel with its top edge at y_top. Returns (lines, y_bottom)."""
    end_s = max(s["t1_us"] for s in spans) / 1e6
    threads = sorted({s["thread"] for s in spans})
    row_of = {t: i for i, t in enumerate(threads)}
    sx = PANEL_W / end_s

    out = [f"% --- {label} ---",
           f"\\node[anchor=west, font=\\scriptsize\\bfseries] at (0,{y_top + 0.42:.2f}) "
           f"{{{label}}};"]

    for s in spans:
        r = row_of[s["thread"]]
        y = y_top - r * ROW_H
        x0, x1 = s["t0_us"] / 1e6 * sx, s["t1_us"] / 1e6 * sx
        colour, _ = KIND_STYLE.get(s["kind"], ("black!30", "?"))
        # A sub-pixel bar is invisible; floor the width so a fast call still
        # shows as a tick rather than vanishing. Never widen a slow one.
        x1 = max(x1, x0 + 0.035)
        out.append(f"\\fill[{colour}] ({x0:.3f},{y:.3f}) rectangle ({x1:.3f},{y - BAR_H:.3f});")

    y_bottom = y_top - (len(threads) - 1) * ROW_H - BAR_H

    # Thread labels, only when there is more than one -- a single "t0" is noise.
    if len(threads) > 1:
        for t, r in row_of.items():
            out.append(f"\\node[anchor=east, font=\\tiny] at (-0.08,"
                       f"{y_top - r * ROW_H - BAR_H / 2:.3f}) {{t{t}}};")

    axis_y = y_bottom - 0.16
    out.append(f"\\draw[black!55, line width=0.3pt] (0,{axis_y:.3f}) -- ({PANEL_W:.2f},{axis_y:.3f});")
    for tick in nice_ticks(end_s):
        x = tick * sx
        out.append(f"\\draw[black!55, line width=0.3pt] ({x:.3f},{axis_y:.3f}) -- ({x:.3f},{axis_y - 0.08:.3f});")
        out.append(f"\\node[anchor=north, font=\\tiny] at ({x:.3f},{axis_y - 0.10:.3f}) {{{tick:g}}};")
    out.append(f"\\node[anchor=west, font=\\tiny] at ({PANEL_W + 0.12:.2f},{axis_y:.3f}) {{s}};")
    return out, axis_y - 0.42


def main() -> int:
    dest, rest = sys.argv[1], sys.argv[2:]
    pairs = list(zip(rest[0::2], rest[1::2]))

    body = ["% GENERATED by e2e/helpers/plot_timeline.py -- do not edit by hand.",
            "\\begin{tikzpicture}[x=1cm, y=1cm]"]
    y = 0.0
    used = set()
    for path, label in pairs:
        spans = load(path)
        used.update(s["kind"] for s in spans)
        lines, y = panel(spans, label, y)
        body.extend(lines)
        y -= PANEL_GAP - 0.42

    # Legend: only kinds that actually appear, so a panel set without writes
    # does not advertise a "create" colour nobody can find.
    x = 0.0
    for kind in (k for k in KIND_STYLE if k in used):
        colour, short = KIND_STYLE[kind]
        body.append(f"\\fill[{colour}] ({x:.2f},{y:.2f}) rectangle ({x + 0.30:.2f},{y - 0.18:.2f});")
        body.append(f"\\node[anchor=west, font=\\tiny] at ({x + 0.36:.2f},{y - 0.09:.2f}) {{{short}}};")
        x += 1.55
    body.append("\\end{tikzpicture}")

    with open(dest, "w") as fh:
        fh.write("\n".join(body) + "\n")
    print(f"wrote {dest} ({len(pairs)} panels)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
