"""Turn helpers.latency_breakdown JSON into the paper's stacked-bar figure.

    python -m helpers.plot_breakdown breakdown.json > ../docs/paper/fig_breakdown.tex

Emits a standalone pgfplots `tikzpicture` -- no image file, so the figure
inherits the document's fonts and stays diffable in git.

DNS, TCP and TLS are merged into one "connect" segment. Measured separately
(they are, in the JSON) they are 0.7 / ~17 / ~34 ms, and three segments of
that size are invisible next to a 1200 ms bar while making the legend twice
as long. `send` is dropped for the same reason: it is 0.0 ms at every shape,
because the request is a few hundred bytes into a local socket buffer.
"""

from __future__ import annotations

import json
import sys

# Order matters: this is the stacking order, left to right.
SEGMENTS = [
    ("connect", "connect", "gray!55"),
    ("ttfb", "server (TTFB)", "blue!55"),
    ("body", "transfer", "orange!75"),
]

# Short labels; the caption carries the detail.
SHORT = {
    "files.list": "files.list",
    "files.get": "files.get",
    "alt=media, whole small file": "media, small file",
    "alt=media, 1 KiB range": "media, 1\\,KiB range",
    "alt=media, 1 MiB range": "media, 1\\,MiB range",
    "alt=media, 16 MiB range": "media, 16\\,MiB range",
}


def rows(data: dict):
    for label, r in data.items():
        for kind in ("cold", "warm"):
            p = r[kind]
            yield (f"{SHORT.get(label, label)} ({kind})",
                   {"connect": p["dns"] + p["tcp"] + p["tls"] + p["send"],
                    "ttfb": p["ttfb"],
                    "body": p["body"]})


def main() -> int:
    data = json.load(open(sys.argv[1]))
    entries = list(rows(data))
    ticks = ", ".join(f"{{{name}}}" for name, _ in entries)

    out = [
        "% GENERATED by e2e/helpers/plot_breakdown.py -- do not edit by hand.",
        "\\begin{tikzpicture}",
        "\\begin{axis}[",
        # Narrow: the y tick labels are wide, and axis width excludes them, so
        # anything above ~0.5 pushes the legend past the column edge.
        "  xbar stacked, width=0.50\\columnwidth, height=7.2cm,",
        "  bar width=6pt, xmin=0, xmax=2200,",
        "  scaled x ticks=false, xtick={0,1000,2000},",
        "  xlabel={milliseconds}, xlabel near ticks,",
        f"  ytick=data, symbolic y coords={{{ticks}}},",
        "  y dir=reverse, yticklabel style={font=\\scriptsize},",
        "  xticklabel style={font=\\scriptsize}, tick align=outside,",
        "  legend style={font=\\scriptsize, at={(0.5,-0.16)}, anchor=north,",
        "                legend columns=3, draw=none},",
        "  every axis plot/.append style={draw=black!40, line width=0.2pt},",
        "]",
    ]
    for key, legend, colour in SEGMENTS:
        pts = " ".join(f"({v[key]:.1f},{{{name}}})" for name, v in entries)
        out.append(f"\\addplot[fill={colour}] coordinates {{{pts}}};")
        out.append(f"\\addlegendentry{{{legend}}}")
    out += ["\\end{axis}", "\\end{tikzpicture}"]
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
